import { Suggestion } from '@/types';

export const themeSuggestions: Suggestion[] = [
  { label: 'Honesty & Truth', value: 'the importance of telling the truth' },
  { label: 'Friendship & Loyalty', value: 'the power of true friendship and loyalty' },
  { label: 'Courage & Bravery', value: 'finding courage in the face of fear' },
  { label: 'Kindness & Compassion', value: 'showing kindness and compassion to others' },
  { label: 'Perseverance', value: 'never giving up, even when things are hard' },
  { label: 'Accepting Differences', value: 'accepting and celebrating our differences' },
  { label: 'Found Family', value: 'finding family in unexpected places' },
  { label: 'Self-Belief', value: 'believing in yourself and your abilities' },
  { label: 'Forgiveness', value: 'the healing power of forgiveness' },
  { label: 'Responsibility', value: 'taking responsibility for your actions' },
  { label: 'Sharing & Generosity', value: 'the joy of sharing and being generous' },
  { label: 'Overcoming Fear', value: 'facing and overcoming your fears' },
  { label: 'Teamwork', value: 'working together to achieve great things' },
  { label: 'Being Yourself', value: 'being true to who you are' },
  { label: 'Helping Others', value: 'the importance of helping those in need' },
];

export const characterNameSuggestions: Suggestion[] = [
  { label: 'Luna', value: 'Luna' },
  { label: 'Max', value: 'Max' },
  { label: 'Zara', value: 'Zara' },
  { label: 'Oliver', value: 'Oliver' },
  { label: 'Mira', value: 'Mira' },
  { label: 'Atlas', value: 'Atlas' },
  { label: 'Nova', value: 'Nova' },
  { label: 'Felix', value: 'Felix' },
  { label: 'Sage', value: 'Sage' },
  { label: 'Rowan', value: 'Rowan' },
  { label: 'Aria', value: 'Aria' },
  { label: 'Jasper', value: 'Jasper' },
  { label: 'Willow', value: 'Willow' },
  { label: 'Phoenix', value: 'Phoenix' },
  { label: 'Ivy', value: 'Ivy' },
  { label: 'Finn', value: 'Finn' },
  { label: 'Aurora', value: 'Aurora' },
  { label: 'Orion', value: 'Orion' },
  { label: 'Hazel', value: 'Hazel' },
  { label: 'Kai', value: 'Kai' },
];

export const settingSuggestions: Suggestion[] = [
  { label: 'Enchanted Forest', value: 'a mysterious enchanted forest' },
  { label: 'Haunted Castle', value: 'an ancient haunted castle' },
  { label: 'Magical Library', value: 'a vast magical library' },
  { label: 'Underwater Kingdom', value: 'a hidden underwater kingdom' },
  { label: 'Floating Islands', value: 'mystical floating islands in the sky' },
  { label: 'Desert Oasis', value: 'a magical desert oasis' },
  { label: 'Crystal Caverns', value: 'glittering crystal caverns deep underground' },
  { label: 'Cloud City', value: 'a magnificent city built on clouds' },
  { label: 'Volcanic Mountain', value: 'a mystical volcanic mountain' },
  { label: 'Frozen Tundra', value: 'an enchanted frozen tundra' },
  { label: 'Moonlit Garden', value: 'a secret moonlit garden' },
  { label: 'Ancient Ruins', value: 'mysterious ancient ruins' },
  { label: 'Starlight Valley', value: 'a peaceful starlight valley' },
  { label: 'Shadow Realm', value: 'the mysterious shadow realm' },
  { label: 'Rainbow Bridge', value: 'a magical rainbow bridge between worlds' },
  { label: 'Whispering Woods', value: 'the whispering woods of old magic' },
  { label: 'Time Tower', value: 'a tower that exists outside of time' },
  { label: 'Dream Dimension', value: 'the ever-shifting dream dimension' },
  { label: 'Coral Palace', value: 'a beautiful coral palace beneath the waves' },
  { label: 'Mountain Peak', value: 'the highest mountain peak in the realm' },
];

export const villainSuggestions: Suggestion[] = [
  { label: 'Shadow King', value: 'the Shadow King' },
  { label: 'Ice Queen', value: 'the Ice Queen' },
  { label: 'Dark Sorcerer', value: 'a dark sorcerer' },
  { label: 'Storm Witch', value: 'the Storm Witch' },
  { label: 'Nightmare Dragon', value: 'a fearsome nightmare dragon' },
  { label: 'Trickster Spirit', value: 'a mischievous trickster spirit' },
  { label: 'Void Keeper', value: 'the mysterious Void Keeper' },
  { label: 'Chaos Wizard', value: 'a chaotic wizard' },
  { label: 'Frost Giant', value: 'an ancient frost giant' },
  { label: 'Phantom Lord', value: 'the Phantom Lord' },
  { label: 'Cursed Knight', value: 'a cursed knight' },
  { label: 'Sea Serpent', value: 'a massive sea serpent' },
  { label: 'Time Thief', value: 'the cunning Time Thief' },
  { label: 'Mirror Demon', value: 'a mirror demon' },
  { label: 'Poison Ivy Queen', value: 'the Poison Ivy Queen' },
  { label: 'Thunder Titan', value: 'the Thunder Titan' },
  { label: 'Bone Collector', value: 'the eerie Bone Collector' },
  { label: 'Dream Eater', value: 'a terrifying dream eater' },
  { label: 'Crystal Tyrant', value: 'the Crystal Tyrant' },
  { label: 'Smoke Wraith', value: 'a mysterious smoke wraith' },
];

export const specialItemSuggestions: Suggestion[] = [
  { label: 'Glowing Crystal', value: 'a glowing crystal' },
  { label: 'Ancient Key', value: 'an ancient golden key' },
  { label: 'Magic Compass', value: 'a magic compass' },
  { label: 'Enchanted Book', value: 'an enchanted spellbook' },
  { label: 'Mysterious Amulet', value: 'a mysterious amulet' },
  { label: 'Singing Sword', value: 'a singing sword' },
  { label: 'Phoenix Feather', value: 'a phoenix feather' },
  { label: 'Time Hourglass', value: 'a magical time hourglass' },
  { label: 'Star Map', value: 'an ancient star map' },
  { label: 'Healing Potion', value: 'a powerful healing potion' },
  { label: 'Dragon Scale', value: 'a shimmering dragon scale' },
  { label: 'Moon Stone', value: 'a glowing moon stone' },
  { label: 'Invisible Cloak', value: 'an invisible cloak' },
  { label: 'Truth Mirror', value: 'a mirror that shows truth' },
  { label: 'Wishing Ring', value: 'a magical wishing ring' },
  { label: 'Spirit Lantern', value: 'a spirit lantern' },
  { label: 'Memory Orb', value: 'a memory orb' },
  { label: 'Wind Flute', value: 'a wind-controlling flute' },
  { label: 'Shadow Cloak', value: 'a cloak woven from shadows' },
  { label: 'Heart Gem', value: 'a gem that glows with courage' },
];

export const characterTraitSuggestions: Suggestion[] = [
  { label: 'Brave and Curious', value: 'brave and endlessly curious' },
  { label: 'Kind and Clever', value: 'kind-hearted and clever' },
  { label: 'Bold and Creative', value: 'bold and creative' },
  { label: 'Gentle and Wise', value: 'gentle and wise beyond their years' },
  { label: 'Playful and Determined', value: 'playful yet determined' },
  { label: 'Thoughtful and Courageous', value: 'thoughtful and courageous' },
  { label: 'Loyal and Fierce', value: 'fiercely loyal' },
  { label: 'Witty and Resourceful', value: 'witty and resourceful' },
  { label: 'Compassionate and Strong', value: 'compassionate yet strong' },
  { label: 'Mysterious and Insightful', value: 'mysterious and insightful' },
  { label: 'Energetic and Optimistic', value: 'energetic and optimistic' },
  { label: 'Patient and Observant', value: 'patient and observant' },
  { label: 'Adventurous and Free-spirited', value: 'adventurous and free-spirited' },
  { label: 'Honest and Trustworthy', value: 'honest and trustworthy' },
  { label: 'Imaginative and Dreamy', value: 'imaginative and dreamy' },
  { label: 'Protective and Caring', value: 'protective and caring' },
  { label: 'Quick-thinking and Agile', value: 'quick-thinking and agile' },
  { label: 'Humble and Powerful', value: 'humble yet powerful' },
  { label: 'Cheerful and Resilient', value: 'cheerful and resilient' },
  { label: 'Studious and Magical', value: 'studious with natural magic' },
];

export const goalSuggestions: Suggestion[] = [
  { label: 'Save the Kingdom', value: 'save the kingdom from eternal darkness' },
  { label: 'Find Lost Treasure', value: 'find the lost treasure of the ancients' },
  { label: 'Break the Curse', value: 'break a terrible curse' },
  { label: 'Rescue a Friend', value: 'rescue their best friend' },
  { label: 'Restore Balance', value: 'restore balance to the magical world' },
  { label: 'Prove Their Worth', value: 'prove their worth as a hero' },
  { label: 'Stop the Darkness', value: 'stop the spreading darkness' },
  { label: 'Unite the Clans', value: 'unite the warring clans' },
  { label: 'Awaken Ancient Magic', value: 'awaken the ancient magic' },
  { label: 'Protect the Innocent', value: 'protect the innocent from harm' },
  { label: 'Discover Their Destiny', value: 'discover their true destiny' },
  { label: 'Heal the Land', value: 'heal the poisoned land' },
  { label: 'Defeat the Prophecy', value: 'defy a dark prophecy' },
  { label: 'Recover Lost Memories', value: 'recover their lost memories' },
  { label: 'Close the Portal', value: 'close the portal to the dark realm' },
  { label: 'Find Their Family', value: 'find their long-lost family' },
  { label: 'Master Their Powers', value: 'master their newfound powers' },
  { label: 'Save the Creatures', value: 'save the magical creatures' },
  { label: 'Restore Peace', value: 'restore peace between worlds' },
  { label: 'Unlock the Secret', value: 'unlock an ancient secret' },
];

export const timePeriodSuggestions: Suggestion[] = [
  { label: 'Medieval Fantasy', value: 'medieval fantasy times' },
  { label: 'Ancient Mythology', value: 'the age of ancient myths' },
  { label: 'Victorian Era', value: 'Victorian steampunk era' },
  { label: 'Future Fantasy', value: 'a magical distant future' },
  { label: 'Timeless Realm', value: 'a timeless magical realm' },
  { label: 'Renaissance', value: 'the magical renaissance' },
  { label: 'Stone Age Magic', value: 'the age of primal magic' },
  { label: 'Golden Age', value: 'the golden age of heroes' },
  { label: 'Dark Ages', value: 'the mysterious dark ages' },
  { label: 'Age of Discovery', value: 'the age of magical discovery' },
  { label: 'Feudal Japan', value: 'mystical feudal Japan' },
  { label: 'Ancient Egypt', value: 'ancient Egypt with magic' },
  { label: 'Norse Era', value: 'the time of Norse legends' },
  { label: 'Celtic Times', value: 'ancient Celtic times' },
  { label: 'Atlantean Age', value: 'the age of Atlantis' },
  { label: 'Wild West Magic', value: 'the magical wild west' },
  { label: 'Space Age Fantasy', value: 'a space age with magic' },
  { label: 'Prehistoric Magic', value: 'prehistoric times with magic' },
  { label: 'Roaring Twenties', value: 'the magical roaring twenties' },
  { label: 'Eternal Present', value: 'an eternal magical present' },
];

export const moodSuggestions: Suggestion[] = [
  { label: 'Mysterious & Adventurous', value: 'mysterious and adventurous' },
  { label: 'Whimsical & Light', value: 'whimsical and lighthearted' },
  { label: 'Epic & Heroic', value: 'epic and heroic' },
  { label: 'Dark & Spooky', value: 'dark and delightfully spooky' },
  { label: 'Wonder & Discovery', value: 'full of wonder and discovery' },
  { label: 'Magical & Dreamy', value: 'magical and dreamy' },
  { label: 'Thrilling & Suspenseful', value: 'thrilling and suspenseful' },
  { label: 'Heartwarming & Cozy', value: 'heartwarming and cozy' },
  { label: 'Action-Packed', value: 'action-packed and exciting' },
  { label: 'Peaceful & Serene', value: 'peaceful and serene' },
  { label: 'Eerie & Enchanting', value: 'eerie yet enchanting' },
  { label: 'Humorous & Fun', value: 'humorous and fun' },
  { label: 'Dramatic & Intense', value: 'dramatic and intense' },
  { label: 'Inspiring & Uplifting', value: 'inspiring and uplifting' },
  { label: 'Melancholic & Beautiful', value: 'melancholic yet beautiful' },
  { label: 'Chaotic & Wild', value: 'chaotic and wild' },
  { label: 'Gentle & Thoughtful', value: 'gentle and thoughtful' },
  { label: 'Tense & Gripping', value: 'tense and gripping' },
  { label: 'Joyful & Celebratory', value: 'joyful and celebratory' },
  { label: 'Bittersweet & Poignant', value: 'bittersweet and poignant' },
];
